请求添加简体语言文件
KyleLin921021/BetterOverlay pull request #1
Opened 2020-12-27 12:48 UTC by LinLei0102

2020-12-27 12:52 UTC, LinLei0102 commented
> _No description provided._

这里是林雷，提交一份我自己翻好的简体文件（已经弄过语法校对了）
希望作者大大能通过，后续会在巴哈进行搬运询问owo

2020-12-27 13:38 UTC, ChAoSUnItY requested changes
格式錯誤，請把zh_CN.json放到src/main/resources/assets/info_is_power/lang裡面，不是自己再開一個資料夾。

2020-12-28 10:13 UTC, ChAoSUnItY approved these changes
好吧，我還是直接接受你的PR。 ;-P

2020-12-28 10:13 UTC, merged

2020-12-28 15:09 UTC, LinLei0102 commented
> 格式錯誤，請把zh_CN.json放到src/main/resources/assets/info_is_power/lang裡面，不是自己再開一個資料夾。

抱歉，第一次使用GitHub上传QWQ
我太南了